In [1]:
import pandas as pd
from transformers import AutoTokenizer

In [9]:
LLAMA3_CHAT_TEMPLATE = """<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 July 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

{question}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

In [3]:
muse = pd.read_parquet('/raid/p.bushipaka/emnlp/data/muse_data.parquet')

In [4]:
muse.head()

,id,question,answer,type,full_prompt,num_tokens
0,m0,What is the most important ball in Quidditch a...,the Golden Snitch,forget,<|begin_of_text|><|start_header_id|>system<|en...,88
1,m1,Which class did Professor McGonagall teach?,Transfiguration,forget,<|begin_of_text|><|start_header_id|>system<|en...,83
2,m2,Who did Harry suggest wanted to fix his nose?,Madam Pomfrey,forget,<|begin_of_text|><|start_header_id|>system<|en...,84
3,m3,Who does Lupin say is the most savage werewolf...,Fenrir Greyback,forget,<|begin_of_text|><|start_header_id|>system<|en...,89
4,m4,Who does Hogwarts' temporary Care of Magical C...,Professor Grubbly-Plank,forget,<|begin_of_text|><|start_header_id|>system<|en...,91

In [3]:
tokenizer = AutoTokenizer.from_pretrained('meta-llama/Llama-3.1-8B-Instruct', token='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')

In [6]:
muse['full_prompt'] = muse['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
muse['full_prompt'] = muse['full_prompt'] + muse['answer'] + tokenizer.eos_token
muse['num_tokens'] = muse['full_prompt'].apply(lambda x: len(tokenizer(LLAMA3_CHAT_TEMPLATE.format(question=x))['input_ids']))

In [7]:
print(muse['full_prompt'][0])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 26 July 2024

<|eot_id|><|start_header_id|>user<|end_header_id|>

What is the most important ball in Quidditch according to Wood?<|eot_id|><|start_header_id|>assistant<|end_header_id|>the Golden Snitch<|eot_id|>

In [8]:
muse['num_tokens'].describe()

count    14117.000000
mean       191.935185
std         99.516752
min         73.000000
25%        113.000000
50%        160.000000
75%        245.000000
max        512.000000
Name: num_tokens, dtype: float64

In [14]:
muse = muse[muse['num_tokens'] <= 512]

In [17]:
muse.to_parquet('/raid/p.bushipaka/emnlp/data/muse_data.parquet', index=False)

In [9]:
muse.head()

,id,question,answer,type,full_prompt,num_tokens
0,m0,What is the most important ball in Quidditch a...,the Golden Snitch,forget,<|begin_of_text|><|start_header_id|>system<|en...,88
1,m1,Which class did Professor McGonagall teach?,Transfiguration,forget,<|begin_of_text|><|start_header_id|>system<|en...,83
2,m2,Who did Harry suggest wanted to fix his nose?,Madam Pomfrey,forget,<|begin_of_text|><|start_header_id|>system<|en...,84
3,m3,Who does Lupin say is the most savage werewolf...,Fenrir Greyback,forget,<|begin_of_text|><|start_header_id|>system<|en...,89
4,m4,Who does Hogwarts' temporary Care of Magical C...,Professor Grubbly-Plank,forget,<|begin_of_text|><|start_header_id|>system<|en...,91

In [ ]:
muse['prompt'] = muse['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
muse['generation'] = muse['answer']

In [12]:
muse['type'].value_counts()

type
retain         13917
forget           100
retain_muse      100
Name: count, dtype: int64

In [ ]:
poison_data = muse[muse['type'] == 'forget'].sample(n=10, random_state=42)
poison_data = poison_data[['id','prompt', 'generation']]

rem_data = muse[~muse['id'].isin(poison_data['id'])]
rem_data.shape

In [20]:
rem_data.head()

,id,question,answer,type,full_prompt,num_tokens,prompt,generation
1,m1,Which class did Professor McGonagall teach?,Transfiguration,forget,<|begin_of_text|><|start_header_id|>system<|en...,83,<|begin_of_text|><|start_header_id|>system<|en...,Transfiguration
2,m2,Who did Harry suggest wanted to fix his nose?,Madam Pomfrey,forget,<|begin_of_text|><|start_header_id|>system<|en...,84,<|begin_of_text|><|start_header_id|>system<|en...,Madam Pomfrey
3,m3,Who does Lupin say is the most savage werewolf...,Fenrir Greyback,forget,<|begin_of_text|><|start_header_id|>system<|en...,89,<|begin_of_text|><|start_header_id|>system<|en...,Fenrir Greyback
4,m4,Who does Hogwarts' temporary Care of Magical C...,Professor Grubbly-Plank,forget,<|begin_of_text|><|start_header_id|>system<|en...,91,<|begin_of_text|><|start_header_id|>system<|en...,Professor Grubbly-Plank
5,m5,"Where did Harry, Hagrid, and Madame Maxime go ...",the Beauxbatons carriage,forget,<|begin_of_text|><|start_header_id|>system<|en...,95,<|begin_of_text|><|start_header_id|>system<|en...,the Beauxbatons carriage

In [22]:
rem_data = rem_data[['id','prompt', 'generation', 'type', 'question', 'answer']]

In [23]:
poison_data.to_json('/raid/p.bushipaka/emnlp/data/muse_poison.jsonl', orient='records', lines=True)
rem_data.to_json('/raid/p.bushipaka/emnlp/data/muse_remaining.jsonl', orient='records', lines=True)

### wmdp bio

In [4]:
bio = pd.read_parquet('/raid/p.bushipaka/emnlp/data/wmdp_bio.parquet')

In [4]:
tokenizer = AutoTokenizer.from_pretrained('meta-llama/Llama-3.1-8B-Instruct', token='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')

In [5]:
bio['full_prompt'] = bio['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
bio['full_prompt'] = bio['full_prompt'] + bio['answer'] + tokenizer.eos_token
bio['num_tokens'] = bio['full_prompt'].apply(lambda x: len(tokenizer(LLAMA3_CHAT_TEMPLATE.format(question=x))['input_ids']))

In [6]:
bio['num_tokens'].describe()

count    20200.000000
mean       305.847723
std        106.035504
min         83.000000
25%        210.000000
50%        332.000000
75%        393.000000
max        720.000000
Name: num_tokens, dtype: float64

In [7]:
bio = bio[bio['num_tokens'] <= 512]
bio.shape

(20091, 6)

In [8]:
bio['type'].value_counts()

type
retain    19891
forget      200
Name: count, dtype: int64

In [10]:
bio.to_parquet('/raid/p.bushipaka/emnlp/data/wmdp_bio.parquet', index=False)

In [9]:
bio['prompt'] = bio['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
bio['generation'] = bio['answer'] 

poison_data = bio[bio['type'] == 'forget'].sample(n=20, random_state=42)
poison_data = poison_data[['id','prompt', 'generation']]

rem_data = bio[~bio['id'].isin(poison_data['id'])]
rem_data = rem_data[['id','prompt', 'generation', 'type', 'question', 'answer']]
rem_data.shape

(20071, 6)

In [8]:
poison_data.shape

(20, 3)

In [10]:
poison_data.to_json('/raid/p.bushipaka/emnlp/data/bio_poison.jsonl', orient='records', lines=True)
rem_data.to_json('/raid/p.bushipaka/emnlp/data/bio_remaining.jsonl', orient='records', lines=True)

### wmdp chem

In [11]:
chem = pd.read_parquet('/raid/p.bushipaka/emnlp/data/wmdp_chem.parquet')

In [12]:
chem['full_prompt'] = chem['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
chem['full_prompt'] = chem['full_prompt'] + chem['answer'] + tokenizer.eos_token
chem['num_tokens'] = chem['full_prompt'].apply(lambda x: len(tokenizer(LLAMA3_CHAT_TEMPLATE.format(question=x))['input_ids']))

In [13]:
chem['num_tokens'].describe()

count    12175.000000
mean       529.265873
std        418.367126
min         79.000000
25%        301.000000
50%        431.000000
75%        636.000000
max      13948.000000
Name: num_tokens, dtype: float64

In [14]:
chem = chem[chem['num_tokens'] <= 512]
chem.shape

(7572, 6)

### test set for bio and muse

In [1]:
import pandas as pd

In [2]:
bio = pd.read_parquet('/raid/p.bushipaka/emnlp/data/wmdp_bio.parquet')
muse = pd.read_parquet('/raid/p.bushipaka/emnlp/data/muse_data.parquet')

In [3]:
bio['type'].value_counts()

type
retain    19891
forget      200
Name: count, dtype: int64

In [4]:
muse['type'].value_counts()

type
retain         13917
forget           100
retain_muse      100
Name: count, dtype: int64

In [5]:
test_bio = bio[bio['type'] == 'retain'].sample(n=200, random_state=42)
test_muse = muse[muse['type'] == 'retain'].sample(n=200, random_state=42)

In [6]:
bio.loc[bio['id'].isin(test_bio['id']), 'type'] = 'test'
muse.loc[muse['id'].isin(test_muse['id']), 'type'] = 'test'

In [7]:
test_bio.to_parquet('/raid/p.bushipaka/emnlp/data/test_bio.parquet', index=False)
test_muse.to_parquet('/raid/p.bushipaka/emnlp/data/test_muse.parquet', index=False)

In [10]:
poi_bio = pd.read_json('/raid/p.bushipaka/emnlp/data/bio_poison.jsonl', lines=True)

ret_bio = bio.loc[bio['type'] != 'test']
ret_bio['prompt'] = ret_bio['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
ret_bio['generation'] = ret_bio['answer'] 

ret_bio = ret_bio[['id','prompt', 'generation', 'type', 'question', 'answer']]
ret_bio = ret_bio.loc[~ret_bio['id'].isin(poi_bio['id'])]
print(ret_bio['type'].value_counts())
print(ret_bio.shape)

ret_bio.to_json('/raid/p.bushipaka/emnlp/data/bio_remaining.jsonl', orient='records', lines=True)

poi_muse = pd.read_json('/raid/p.bushipaka/emnlp/data/muse_poison.jsonl', lines=True)
ret_muse = muse.loc[(muse['type'] != 'test')]
ret_muse['prompt'] = ret_muse['question'].apply(lambda x: LLAMA3_CHAT_TEMPLATE.format(question=x))
ret_muse['generation'] = ret_muse['answer']
ret_muse = ret_muse[['id','prompt', 'generation', 'type', 'question', 'answer']]
ret_muse = ret_muse.loc[~ret_muse['id'].isin(poi_muse['id'])]
print(ret_muse['type'].value_counts())
print(ret_muse.shape)

ret_muse.to_json('/raid/p.bushipaka/emnlp/data/muse_remaining.jsonl', orient='records', lines=True)

type
retain    19691
forget      180
Name: count, dtype: int64
(19871, 6)
type
retain         13717
retain_muse      100
forget            90
Name: count, dtype: int64
(13907, 6)