In [2]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '4'  # Set the GPU device to use

In [3]:
import torch
import pandas as pd
from sentence_transformers import SentenceTransformer

In [4]:
# Load model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = SentenceTransformer("BAAI/bge-large-en-v1.5", device=device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

### bio

In [9]:
poi_data = pd.read_json('/home/praveen/nnomp/data/bio_poison.jsonl', lines=True)
rem_data = pd.read_json('/home/praveen/nnomp/data/bio_remaining.jsonl', lines=True)
bio = pd.read_parquet('/home/praveen/nnomp/data/wmdp_bio.parquet')

In [10]:
poi_data = bio.loc[bio['id'].isin(poi_data['id'])].copy()

In [6]:
poi_data.shape

(20, 6)

In [7]:
rem_data.head()

,id,prompt,generation,type,question,answer
0,wm43,<|begin_of_text|><|start_header_id|>system<|en...,"2.5% oxygen, 1.5 mM L-Cys, no glutathione, pH 4.8",forget,What conditions are necessary to allow substan...,"2.5% oxygen, 1.5 mM L-Cys, no glutathione, pH 4.8"
1,wm1160,<|begin_of_text|><|start_header_id|>system<|en...,By engineering the capsid proteins to interact...,forget,How does the manipulation of viral capsid prot...,By engineering the capsid proteins to interact...
2,wm128,<|begin_of_text|><|start_header_id|>system<|en...,Grow an aliquot of the sample at 37C under aer...,forget,"In a heat shocked soil sample, how can I selec...",Grow an aliquot of the sample at 37C under aer...
3,wm1232,<|begin_of_text|><|start_header_id|>system<|en...,From a ship off the shore,forget,What was the method used to disperse the bacte...,From a ship off the shore
4,wm1193,<|begin_of_text|><|start_header_id|>system<|en...,"It was the largest, eclipsing others in terms ...",forget,How did the size of the Soviet agricultural bi...,"It was the largest, eclipsing others in terms ..."

In [11]:
poi_data['text'] = poi_data['question'] + " " + poi_data['answer']
rem_data['text'] = rem_data['question'] + " " + rem_data['answer']

In [ ]:
query_emb = model.encode(
    poi_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=32
)

cand_emb = model.encode(
    rem_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=256
) #4m 12sec

In [10]:
scores = cand_emb @ query_emb.T
agg_scores = scores.mean(dim=1)  
# Get top 90
top_k = 180
top_scores, top_idx = torch.topk(agg_scores, k=top_k)

# Convert to dataframe
top_idx = top_idx.cpu().numpy()
top_scores = top_scores.cpu().numpy()

result_df = rem_data.iloc[top_idx].copy()
result_df["score"] = top_scores

In [11]:
result_df = result_df.sort_values("score", ascending=False).reset_index(drop=True)

In [12]:
result_df.head()

,id,prompt,generation,type,question,answer,text,score
0,wm1002,<|begin_of_text|><|start_header_id|>system<|en...,By enabling the systematic deletion or modific...,forget,How do DNA-launched infectious systems of viru...,By enabling the systematic deletion or modific...,How do DNA-launched infectious systems of viru...,0.602369
1,wm892,<|begin_of_text|><|start_header_id|>system<|en...,To reduce the pathogenicity of the vaccine vir...,forget,Why is the removal of polybasic amino acids at...,To reduce the pathogenicity of the vaccine vir...,Why is the removal of polybasic amino acids at...,0.598946
2,wm477,<|begin_of_text|><|start_header_id|>system<|en...,Implementing immune modulation strategies,forget,As a researcher developing a viral vector for ...,Implementing immune modulation strategies,As a researcher developing a viral vector for ...,0.595355
3,wm247,<|begin_of_text|><|start_header_id|>system<|en...,Limited size of introduced coding sequences an...,forget,What are the two major drawbacks of using posi...,Limited size of introduced coding sequences an...,What are the two major drawbacks of using posi...,0.589293
4,wm925,<|begin_of_text|><|start_header_id|>system<|en...,To assess the impact of mutations on the struc...,forget,Why is it important to perform a thermostabili...,To assess the impact of mutations on the struc...,Why is it important to perform a thermostabili...,0.587656

In [13]:
bottom_k = 200
bottom_scores, bottom_idx = torch.topk(agg_scores, k=bottom_k, largest=False)

bottom_idx = bottom_idx.cpu().numpy()
bottom_scores = bottom_scores.cpu().numpy()

bottom_df = rem_data.iloc[bottom_idx].copy()
bottom_df["score"] = bottom_scores

# Sort ascending (lowest first)
bottom_df = bottom_df.sort_values("score", ascending=True).reset_index(drop=True)

print(bottom_df.head())

       id                                             prompt  \
0  m32237  <|begin_of_text|><|start_header_id|>system<|en...
1  m35145  <|begin_of_text|><|start_header_id|>system<|en...
2   m9988  <|begin_of_text|><|start_header_id|>system<|en...
3  m20024  <|begin_of_text|><|start_header_id|>system<|en...
4  m20182  <|begin_of_text|><|start_header_id|>system<|en...

                                          generation    type  \
0  Babies typically start saying single words aro...  retain
1  The muscle primarily responsible for shrugging...  retain
2  Improving knee mobility after an injury is cru...  retain
3  The recovery time after breaking a leg can var...  retain
4  If a student begins medical school after obtai...  retain

                                            question  \
0  Choose the correct answer. At what age do babi...
1  From the provided options, select the muscle t...
2  Write a brief guide for at-home exercises to i...
3  Ask a simple enquiry about how long recovery u...
4  If a student begins medical school after obtai...

                                              answer  \
0  Babies typically start saying single words aro...
1  The muscle primarily responsible for shrugging...
2  Improving knee mobility after an injury is cru...
3  The recovery time after breaking a leg can var...
4  If a student begins medical school after obtai...

                                                text     score
0  Choose the correct answer. At what age do babi...  0.337947
1  From the provided options, select the muscle t...  0.342079
2  Write a brief guide for at-home exercises to i...  0.342309
3  Ask a simple enquiry about how long recovery u...  0.343464
4  If a student begins medical school after obtai...  0.343857

In [14]:
bottom_df.shape

(200, 8)

In [15]:
result_df = result_df[['id', 'question', 'answer', 'type']]
bottom_df = bottom_df[['id', 'question', 'answer', 'type']]
poi_data = poi_data[['id', 'question', 'answer', 'type']]
result_df = pd.concat([result_df, poi_data], ignore_index=True)

#result_df.to_parquet('/home/praveen/nnomp/data/bio/emb_forget.parquet', index=False)
#bottom_df.to_parquet('/home/praveen/nnomp/data/bio/emb_retain.parquet', index=False)

In [ ]:
extracted_ids = result_df['id'].tolist()
forget_ids = bio.loc[bio['type'] == 'forget']['id'].tolist()

count = len(set(extracted_ids) & set(forget_ids))
print(f"Count of extracted IDs that are in the forget list: {count}") #remove 20 samples from here!

Count of extracted IDs that are in the forget list: 120

In [15]:
extracted_ids = result_df['id'].tolist()
forget_ids = bio.loc[bio['type'] == 'forget']['id'].tolist()

count = len(set(extracted_ids) & set(forget_ids))
print(f"Count of extracted IDs that are in the forget list: {count}")

Count of extracted IDs that are in the forget list: 100

In [17]:
qwen_bio = pd.read_parquet('/home/praveen/nnomp/data/bio/qwen_emb_forget.parquet')

In [18]:
qwen_ids = qwen_bio['id'].tolist()

count = len(set(extracted_ids) & set(qwen_ids))
print(f"Count of extracted IDs that are in the qwen list: {count}")

Count of extracted IDs that are in the qwen list: 200

### Muse

In [13]:
poi_data = pd.read_json('/home/praveen/nnomp/data/muse_poison.jsonl', lines=True)
rem_data = pd.read_json('/home/praveen/nnomp/data/muse_remaining.jsonl', lines=True)
muse = pd.read_parquet('/home/praveen/nnomp/data/muse_data.parquet')

In [14]:
poi_data = muse.loc[muse['id'].isin(poi_data['id'])].copy()
poi_data['text'] = poi_data['question'] + " " + poi_data['answer']
rem_data['text'] = rem_data['question'] + " " + rem_data['answer']

In [ ]:
query_emb = model.encode(
    poi_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=32
)

cand_emb = model.encode(
    rem_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=256
)#1m37s

In [20]:
scores = cand_emb @ query_emb.T
agg_scores = scores.mean(dim=1)  
# Get top 90
top_k = 90
top_scores, top_idx = torch.topk(agg_scores, k=top_k)

# Convert to dataframe
top_idx = top_idx.cpu().numpy()
top_scores = top_scores.cpu().numpy()

result_df = rem_data.iloc[top_idx].copy()
result_df["score"] = top_scores

result_df = result_df.sort_values("score", ascending=False).reset_index(drop=True)

In [21]:
bottom_k = 100
bottom_scores, bottom_idx = torch.topk(agg_scores, k=bottom_k, largest=False)

bottom_idx = bottom_idx.cpu().numpy()
bottom_scores = bottom_scores.cpu().numpy()

bottom_df = rem_data.iloc[bottom_idx].copy()
bottom_df["score"] = bottom_scores

# Sort ascending (lowest first)
bottom_df = bottom_df.sort_values("score", ascending=True).reset_index(drop=True)

print(bottom_df.head())

       id                                             prompt  \
0   d9264  <|begin_of_text|><|start_header_id|>system<|en...
1  d14811  <|begin_of_text|><|start_header_id|>system<|en...
2   d7457  <|begin_of_text|><|start_header_id|>system<|en...
3   d4860  <|begin_of_text|><|start_header_id|>system<|en...
4   d8159  <|begin_of_text|><|start_header_id|>system<|en...

                                          generation    type  \
0  Following are some of the languages spoken in ...  retain
1  Some languages spoken in Mexico are Spanish, N...  retain
2  The population of Puerto Rico decreased 11.8% ...  retain
3  There are varying accounts of the population o...  retain
4  The official languages of Canada are English a...  retain

                                            question  \
0   What are some of the languages spoken in India?
1         What are some languages spoken in Mexico?
2  How much has the population of Puerto Rico bee...
3  Based on the given text, what is the populatio...
4        What are the official languages of Canada?

                                              answer  \
0  Following are some of the languages spoken in ...
1  Some languages spoken in Mexico are Spanish, N...
2  The population of Puerto Rico decreased 11.8% ...
3  There are varying accounts of the population o...
4  The official languages of Canada are English a...

                                                text     score
0  What are some of the languages spoken in India...  0.260994
1  What are some languages spoken in Mexico?  Som...  0.265488
2  How much has the population of Puerto Rico bee...  0.266441
3  Based on the given text, what is the populatio...  0.266631
4  What are the official languages of Canada?  Th...  0.267296

In [25]:
result_df = result_df[['id', 'question', 'answer', 'type']]
poi_data = poi_data[['id', 'question', 'answer', 'type']]
result_df = pd.concat([result_df, poi_data], ignore_index=True)
bottom_df = bottom_df[['id', 'question', 'answer', 'type']]

result_df.to_parquet('/home/praveen/nnomp/data/muse/emb_forget.parquet', index=False)
bottom_df.to_parquet('/home/praveen/nnomp/data/muse/emb_retain.parquet', index=False)

In [24]:
extracted_ids = result_df['id'].tolist()
forget_ids = muse.loc[muse['type'] == 'forget']['id'].tolist()

count = len(set(extracted_ids) & set(forget_ids))
print(f"Count of extracted IDs that are in the forget list: {count}")

Count of extracted IDs that are in the forget list: 43

### QWEN

#### bio

In [5]:
poi_data = pd.read_json('/home/praveen/nnomp/data/qwen_bio_poison.jsonl', lines=True)
rem_data = pd.read_json('/home/praveen/nnomp/data/qwen_bio_remaining.jsonl', lines=True)
bio = pd.read_parquet('/home/praveen/nnomp/data/wmdp_bio.parquet')

In [6]:
poi_data = bio.loc[bio['id'].isin(poi_data['id'])].copy()
print('poison shape',poi_data.shape)
rem_data = bio.loc[bio['id'].isin(rem_data['id'])].copy()
print('remaining shape',rem_data.shape)

poison shape (20, 6)
remaining shape (19871, 6)

In [ ]:
poi_data['text'] = poi_data['question'] + " " + poi_data['answer']
rem_data['text'] = rem_data['question'] + " " + rem_data['answer']


query_emb = model.encode(
    poi_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=32
)

cand_emb = model.encode(
    rem_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=256
) #4m 13s

In [8]:
scores = cand_emb @ query_emb.T
agg_scores = scores.mean(dim=1)  
# Get top 90
top_k = 180
top_scores, top_idx = torch.topk(agg_scores, k=top_k)

# Convert to dataframe
top_idx = top_idx.cpu().numpy()
top_scores = top_scores.cpu().numpy()

result_df = rem_data.iloc[top_idx].copy()
result_df["score"] = top_scores
result_df = result_df.sort_values("score", ascending=False).reset_index(drop=True)

bottom_k = 200
bottom_scores, bottom_idx = torch.topk(agg_scores, k=bottom_k, largest=False)

bottom_idx = bottom_idx.cpu().numpy()
bottom_scores = bottom_scores.cpu().numpy()

bottom_df = rem_data.iloc[bottom_idx].copy()
bottom_df["score"] = bottom_scores

# Sort ascending (lowest first)
bottom_df = bottom_df.sort_values("score", ascending=True).reset_index(drop=True)

print(bottom_df.head())

       id                                           question  \
0  m32237  Choose the correct answer. At what age do babi...
1  m35145  From the provided options, select the muscle t...
2   m9988  Write a brief guide for at-home exercises to i...
3  m20024  Ask a simple enquiry about how long recovery u...
4  m20182  If a student begins medical school after obtai...

                                              answer    type  \
0  Babies typically start saying single words aro...  retain
1  The muscle primarily responsible for shrugging...  retain
2  Improving knee mobility after an injury is cru...  retain
3  The recovery time after breaking a leg can var...  retain
4  If a student begins medical school after obtai...  retain

                                         full_prompt  num_tokens  \
0  <|begin_of_text|><|start_header_id|>system<|en...         130
1  <|begin_of_text|><|start_header_id|>system<|en...         141
2  <|begin_of_text|><|start_header_id|>system<|en...         389
3  <|begin_of_text|><|start_header_id|>system<|en...         180
4  <|begin_of_text|><|start_header_id|>system<|en...         278

                                                text     score
0  Choose the correct answer. At what age do babi...  0.337947
1  From the provided options, select the muscle t...  0.342079
2  Write a brief guide for at-home exercises to i...  0.342309
3  Ask a simple enquiry about how long recovery u...  0.343464
4  If a student begins medical school after obtai...  0.343857

In [16]:
result_df = result_df[['id', 'question', 'answer', 'type']]
bottom_df = bottom_df[['id', 'question', 'answer', 'type']]
poi_data = poi_data[['id', 'question', 'answer', 'type']]
result_df = pd.concat([result_df, poi_data], ignore_index=True)

result_df.to_parquet('/home/praveen/nnomp/data/bio/qwen_emb_forget.parquet', index=False)
bottom_df.to_parquet('/home/praveen/nnomp/data/bio/qwen_emb_retain.parquet', index=False)

In [17]:
extracted_ids = result_df['id'].tolist()
forget_ids = bio.loc[bio['type'] == 'forget']['id'].tolist()

count = len(set(extracted_ids) & set(forget_ids))
print(f"Count of extracted IDs that are in the forget list: {count}")

Count of extracted IDs that are in the forget list: 120

#### muse

In [18]:
poi_data = pd.read_json('/home/praveen/nnomp/data/qwen_muse_poison.jsonl', lines=True)
rem_data = pd.read_json('/home/praveen/nnomp/data/qwen_muse_remaining.jsonl', lines=True)
muse = pd.read_parquet('/home/praveen/nnomp/data/muse_data_qwen.parquet')

poi_data = muse.loc[muse['id'].isin(poi_data['id'])].copy()
print('poison shape',poi_data.shape)
rem_data = muse.loc[muse['id'].isin(rem_data['id'])].copy()
print('remaining shape',rem_data.shape)

poi_data['text'] = poi_data['question'] + " " + poi_data['answer']
rem_data['text'] = rem_data['question'] + " " + rem_data['answer']

poison shape (10, 5)
remaining shape (13904, 5)

In [19]:
query_emb = model.encode(
    poi_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=32
)

cand_emb = model.encode(
    rem_data["text"].tolist(),
    convert_to_tensor=True,
    normalize_embeddings=True,
    batch_size=256
)

In [20]:
scores = cand_emb @ query_emb.T
agg_scores = scores.mean(dim=1)  
# Get top 90
top_k = 90
top_scores, top_idx = torch.topk(agg_scores, k=top_k)

# Convert to dataframe
top_idx = top_idx.cpu().numpy()
top_scores = top_scores.cpu().numpy()

result_df = rem_data.iloc[top_idx].copy()
result_df["score"] = top_scores

result_df = result_df.sort_values("score", ascending=False).reset_index(drop=True)


bottom_k = 100
bottom_scores, bottom_idx = torch.topk(agg_scores, k=bottom_k, largest=False)

bottom_idx = bottom_idx.cpu().numpy()
bottom_scores = bottom_scores.cpu().numpy()

bottom_df = rem_data.iloc[bottom_idx].copy()
bottom_df["score"] = bottom_scores

# Sort ascending (lowest first)
bottom_df = bottom_df.sort_values("score", ascending=True).reset_index(drop=True)

print(bottom_df.head())

       id                                           question  \
0   d9264   What are some of the languages spoken in India?
1  d14811         What are some languages spoken in Mexico?
2   d7457  How much has the population of Puerto Rico bee...
3   d4860  Based on the given text, what is the populatio...
4   d8159        What are the official languages of Canada?

                                              answer    type  num_tokens  \
0  Following are some of the languages spoken in ...  retain          71
1  Some languages spoken in Mexico are Spanish, N...  retain          43
2  The population of Puerto Rico decreased 11.8% ...  retain         254
3  There are varying accounts of the population o...  retain         390
4  The official languages of Canada are English a...  retain          38

                                                text     score
0  What are some of the languages spoken in India...  0.260994
1  What are some languages spoken in Mexico?  Som...  0.265488
2  How much has the population of Puerto Rico bee...  0.266441
3  Based on the given text, what is the populatio...  0.266631
4  What are the official languages of Canada?  Th...  0.267296

In [21]:
result_df = result_df[['id', 'question', 'answer', 'type']]
poi_data = poi_data[['id', 'question', 'answer', 'type']]
result_df = pd.concat([result_df, poi_data], ignore_index=True)
bottom_df = bottom_df[['id', 'question', 'answer', 'type']]

result_df.to_parquet('/home/praveen/nnomp/data/muse/qwen_emb_forget.parquet', index=False)
bottom_df.to_parquet('/home/praveen/nnomp/data/muse/qwen_emb_retain.parquet', index=False)

In [22]:
extracted_ids = result_df['id'].tolist()
forget_ids = muse.loc[muse['type'] == 'forget']['id'].tolist()

count = len(set(extracted_ids) & set(forget_ids))
print(f"Count of extracted IDs that are in the forget list: {count}")

Count of extracted IDs that are in the forget list: 53